# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0023_auto_20190318_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeninganswer',
            old_name='mcq_id',
            new_name='mcq_id0',
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_id1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_id2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_id3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_id4',
            field=models.IntegerField(null=True),
        ),
    ]
