# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0025_auto_20190320_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeninganswer',
            old_name='mcq_idc',
            new_name='mcq_idc0',
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idc1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idc2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idc3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcq_idc4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqc3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='mcqc4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
