# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpaper', '0026_auto_20190320_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillup_idd6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listeninganswer',
            name='fillupd6',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
